
name: 1.0.x

on:
  push:
    branches: [ 1.0.x ]
  pull_request:
    branches: [ 1.0.x ]
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
    - name: Test with pytest
      run: |
        pytest
